version: "3"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  run:
    desc: "Build and run the program"
    cmds:
      - task: build
      - task: run-binary
        vars:
          CLI_ARGS: "{{ .CLI_ARGS }}"
  build:
    desc: "Build the program"
    cmds:
      - go build  -o ./cmd/pkgcollision/pkgcollision ./cmd/pkgcollision
  run-binary:
    desc: "Run builded binary"
    cmds:
      - ./cmd/pkgcollision/pkgcollision {{ .CLI_ARGS }}
  test:
    cmds:
      - go test ./... -v
  update:mod:
    desc: "Update go mod"
    cmds:
      - go get -u ./...
  tidy:mod:
    desc: "Tidy go mod"
    cmds:
      - go mod tidy
  godoc:
    desc: "Host a Godoc web server on the http://localhost:6060/pkg/github.com/hrvadl/converter?m=all"
    deps: [install:godoc]
    cmds:
      - echo "go to the http://localhost:6060/pkg/github.com/hrvadl/converter?m=all"
      - godoc -http=:6060
  install:godoc:
    desc: "Installed godoc util"
    cmds:
      - go install -v golang.org/x/tools/cmd/godoc@latest
    status:
      - command godoc -h
